# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, add-continous-integration  ]
  pull_request:
    branches: [ main, add-continous-integration ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      CC_TEST_REPORTER_ID: bf2d09aff7765a2fa121ffdc437826b1a8b00807da3295e1dc22ee7f803b7f58

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn install
    - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - run: chmod +x ./cc-test-reporter
    - run: ./cc-test-reporter before-build
    # - run: yarn run build --if-present
    - run: yarn run test
    - run: ./cc-test-reporter format-coverage -t lcov --prefix tmp/
    - run: ./cc-test-reporter after-build -t lcov --exit-code $?
